#!/usr/bin/env bash
# Configure my nginx to redirect

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World" | sudo tee /var/www/html/index.html > /dev/null
sudo chmod 777 /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/
sudo sed -i "/listen 80 default_server;/a location /redirect_me {\n return 301 https://www.youtube.com/watch?v=x09sTIjual8 permanent;\n" /etc/nginx/sites-avaiable/default
sudo service nginx restart
sudo service nginx reload
