#!/usr/bin/env bash
# Configure my new server with Nginx header

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod 777 /etc/nginx/sites-enabled/default /etc/nginx/sites-enabled/
sudo sed -i "/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
