#!/usr/bin/env bash
# this script displays 10 times "Best School" excepth in the 9th iterarion
i=1
while [ $i -le 10 ]
do
	if [[ $i == 9 ]]; then
		echo "Best School"
		echo "Hi"
		((i++))
	else
		echo "Best School"
		i=$((i+1))
	fi
done
