#!/usr/bin/env bash
# this script displays 10 times "Best School" excepth in the 9th iterarion
h=0
while [ $h -le 12 ]
do
	echo "Hour: "$h
	m=1
	while [ $m -lt 60 ]; do
		echo $m
		((m++))
	done
	((h++))
done
