#!/usr/bin/env bash
# Run Nginx as Nginx user
sudo chown nginx:nginx /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chmod 777 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
